version: '3.9'
services:
  ghost:
    image: ghost:1-alpine
    ports:
      - 8080:2368
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: password123
      database__connection__database: ghost
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: db
    volumes:
      - ./data/mysql:/var/lib/mysql
